In [1]:
import numpy as np
array = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [86]:
#How many negative numbers are there?
(array < 0).sum()


4

In [87]:
#How many even positive numbers are there?
(array >=0).sum()

8

In [88]:
#How many even positive numbers are there?
even_pos_num = array[(array %2 == 0) & (array > 0)] 
(even_pos_num > 0).sum()

3

In [89]:
#If you were to add 3 to each data point, how many positive numbers would there be?
array_add_3 = array +3
(array_add_3 >= 0).sum()

10

In [52]:
#If you squared each number, what would the new mean and standard deviation be?
array_squared = array **2
print('Squared numbers mean is: ', array_squared.mean())
print('Squared numbers standard deviation is: ',array_squared.std())

Squared numbers mean is:  74.0
Squared numbers standard deviation is:  144.0243035046516


In [ ]:
#A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.


In [54]:
array

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [56]:
array.mean()

3.0

In [59]:
centered_array = array -3

In [60]:
centered_array.mean()

0.0

In [ ]:
#calculate the z-score for each data point. Recall that the z-score is given by:

In [ ]:
#z =(value - mean/std)

In [76]:
z_score = (array - array.mean())/array.std()

In [77]:
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [83]:
# simplified way
z_score2 = centered_array/array.std()

In [84]:
z_score2

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])